In [1]:
import torch 
import numpy as np

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.8026e-45, 0.0000e+00, 1.1210e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.3836, 0.4063, 0.3684],
        [0.2242, 0.4243, 0.0268],
        [0.6650, 0.9154, 0.3475],
        [0.9884, 0.9816, 0.6189],
        [0.7289, 0.3117, 0.1084]])


In [4]:
torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0.3836, 0.4063, 0.3684],
        [0.2242, 0.4243, 0.0268],
        [0.6650, 0.9154, 0.3475],
        [0.9884, 0.9816, 0.6189],
        [0.7289, 0.3117, 0.1084]])


In [5]:
torch.tensor([1.23,3])

tensor([1.2300, 3.0000])

In [6]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.0147,  0.6782,  0.4144],
        [ 0.4576, -0.8856,  1.4949],
        [-0.5797,  2.5663,  2.7044],
        [-0.1954, -0.2208,  0.8503],
        [-0.0217,  1.9212, -1.2333]])


In [9]:
x = torch.arange(0, 19, 2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [12]:
x = torch.linspace(0,3,4)
print(x)

tensor([0., 1., 2., 3.])


In [14]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [15]:
x = torch.tensor([5,6,7],dtype=torch.int)

In [16]:
print(x.dtype)

torch.int32


In [17]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [19]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
